var json_i18n = {
  theme: "Theme",
  dark_gray: "Dark Gray",
  bright: "Bright",
  dark_blue: "Dark Blue",
  dark_purple: "Dark Purple",
  panels: "Panels",
  items_per_page: "Items per Page",
  tables: "Tables",
  display_tables: "Display Tables",
  ah_small: "Auto-Hide on Small Devices",
  ah_small_title: "Automatically hide tables on small screen devices",
  toggle_panel: "Toggle Panel",
  layout: "Layout",
  horizontal: "Horizontal",
  vertical: "Vertical",
  wide: "WideScreen",
  file_opts: "File Options",
  export_json: "Export as JSON",
  panel_opts: "Panel Options",
  previous: "Previous",
  next: "Next",
  first: "First",
  last: "Last",
  chart_opts: "Chart Options",
  chart: "Chart",
  type: "Type",
  area_spline: "Area Spline",
  bar: "Bar",
  plot_metric: "Plot Metric",
  table_columns: "Table Columns",
  thead: "Overall Analyzed Requests",
  version: "1.6.4",
};
var html_prefs = {};
var user_interface = {
  general: {
    head: "Overall Analyzed Requests",
    desc: "",
    items: {
      total_requests: {
        className: "black",
        dataType: "numeric",
        label: "Total Requests",
      },
      valid_requests: {
        className: "green",
        dataType: "numeric",
        label: "Valid Requests",
      },
      failed_requests: {
        className: "red",
        dataType: "numeric",
        label: "Failed Requests",
      },
      generation_time: {
        className: "gray",
        dataType: "secs",
        label: "Log Parsing Time",
      },
      unique_visitors: {
        className: "blue",
        dataType: "numeric",
        label: "Unique Visitors",
      },
      unique_files: { dataType: "numeric", label: "Requested Files" },
      excluded_hits: { dataType: "numeric", label: "Excl. IP Hits" },
      unique_referrers: { dataType: "numeric", label: "Referrers" },
      unique_not_found: { dataType: "numeric", label: "Not Found" },
      unique_static_files: { dataType: "numeric", label: "Static Files" },
      log_size: { dataType: "bytes", label: "Log Size" },
      bandwidth: { dataType: "bytes", label: "Tx. Amount" },
    },
  },
  realtime_requests: {
    head: "Total of request in 24 hours",
    desc: "Top requests sorted by hits [, avgts, cumts, maxts, mthd, proto]",
    id: "realtime_requests",
    table: 1,
    index: 0,
    perPage: 20,
    panelSize: "large",
    sort: { field: "hits", order: "DESC" },
    plot: [],
    items: [
      {
        colWidth: "6%",
        dataType: "string",
        key: "class",
        label: "Label",
      },
      {
        colWidth: "12%",
        dataType: "string",
        key: "ip",
        label: "IP Addr.",
      },
      {
        colWidth: "12%",
        dataType: "string",
        key: "time",
        label: "Timestamp",
      },
      { colWidth: "6%", dataType: "string", key: "method", label: "Method" },
      {
        colWidth: "12%",
        dataType: "string",
        key: "protocol",
        label: "Protocol",
      },
      {
        colWidth: "7%",
        dataType: "string",
        key: "status",
        label: "Status Code",
      },
      {
        className: "trunc",
        colWidth: "100%",
        meta: "unique",
        metaType: "numeric",
        metaLabel: "Total",
        dataType: "string",
        key: "data",
        label: "Data",
      },
    ],
  },
  visitors: {
    head: "Unique visitors per day - Including spiders",
    desc: "Hits having the same IP, date and agent are a unique visit.",
    id: "visitors",
    table: 1,
    index: 1,
    sort: { field: "data", order: "DESC" },
    plot: [
      {
        className: "hits-visitors",
        label: "Hits/Visitors",
        chartType: "area-spline",
        chartReverse: 1,
        redrawOnExpand: 1,
        d3: {
          y0: { key: "hits", label: "Hits" },
          y1: { key: "visitors", label: "Visitors" },
        },
      },
      {
        className: "bandwidth",
        label: "Tx. Amount",
        chartType: "area-spline",
        chartReverse: 1,
        redrawOnExpand: 1,
        d3: { y0: { key: "bytes", label: "Tx. Amount", format: "bytes" } },
      },
    ],
    items: [
      {
        colWidth: "12%",
        meta: "count",
        dataType: "numeric",
        key: "hits",
        label: "Hits",
      },
      {
        colWidth: "12%",
        meta: "count",
        dataType: "numeric",
        key: "visitors",
        label: "Visitors",
      },
      {
        colWidth: "12%",
        meta: "count",
        dataType: "bytes",
        key: "bytes",
        label: "Tx. Amount",
      },
      {
        className: "trunc",
        colWidth: "100%",
        meta: "unique",
        metaType: "numeric",
        metaLabel: "Total",
        dataType: "date",
        key: "data",
        label: "Data",
      },
    ],
  },
  requests: {
    head: "Requested Files (URLs)",
    desc: "Top requests sorted by hits [, avgts, cumts, maxts, mthd, proto]",
    id: "requests",
    table: 1,
    index: 2,
    sort: { field: "hits", order: "DESC" },
    plot: [
      {
        className: "hits-visitors",
        label: "Hits/Visitors",
        chartType: "bar",
        chartReverse: 0,
        redrawOnExpand: 0,
        d3: {
          x: { key: ["method", "data", "protocol"] },
          y0: { key: "hits", label: "Hits" },
          y1: { key: "visitors", label: "Visitors" },
        },
      },
      {
        className: "bandwidth",
        label: "Tx. Amount",
        chartType: "bar",
        chartReverse: 0,
        redrawOnExpand: 0,
        d3: {
          x: { key: ["method", "protocol", "data"] },
          y0: { key: "bytes", label: "Tx. Amount", format: "bytes" },
        },
      },
    ],
    items: [
      {
        colWidth: "12%",
        meta: "count",
        dataType: "numeric",
        key: "hits",
        label: "Hits",
      },
      {
        colWidth: "12%",
        meta: "count",
        dataType: "numeric",
        key: "visitors",
        label: "Visitors",
      },
      {
        colWidth: "12%",
        meta: "count",
        dataType: "bytes",
        key: "bytes",
        label: "Tx. Amount",
      },
      { colWidth: "6%", dataType: "string", key: "method", label: "Method" },
      {
        colWidth: "7%",
        dataType: "string",
        key: "protocol",
        label: "Protocol",
      },
      {
        className: "trunc",
        colWidth: "100%",
        meta: "unique",
        metaType: "numeric",
        metaLabel: "Total",
        dataType: "string",
        key: "data",
        label: "Data",
      },
    ],
  },
  static_requests: {
    head: "Static Requests",
    desc: "Top static requests sorted by hits [, avgts, cumts, maxts, mthd, proto]",
    id: "static_requests",
    table: 1,
    index: 3,
    sort: { field: "hits", order: "DESC" },
    plot: [
      {
        className: "hits-visitors",
        label: "Hits/Visitors",
        chartType: "bar",
        chartReverse: 0,
        redrawOnExpand: 0,
        d3: {
          x: { key: ["method", "data", "protocol"] },
          y0: { key: "hits", label: "Hits" },
          y1: { key: "visitors", label: "Visitors" },
        },
      },
      {
        className: "bandwidth",
        label: "Tx. Amount",
        chartType: "bar",
        chartReverse: 0,
        redrawOnExpand: 0,
        d3: {
          x: { key: ["method", "protocol", "data"] },
          y0: { key: "bytes", label: "Tx. Amount", format: "bytes" },
        },
      },
    ],
    items: [
      {
        colWidth: "12%",
        meta: "count",
        dataType: "numeric",
        key: "hits",
        label: "Hits",
      },
      {
        colWidth: "12%",
        meta: "count",
        dataType: "numeric",
        key: "visitors",
        label: "Visitors",
      },
      {
        colWidth: "12%",
        meta: "count",
        dataType: "bytes",
        key: "bytes",
        label: "Tx. Amount",
      },
      { colWidth: "6%", dataType: "string", key: "method", label: "Method" },
      {
        colWidth: "7%",
        dataType: "string",
        key: "protocol",
        label: "Protocol",
      },
      {
        className: "trunc",
        colWidth: "100%",
        meta: "unique",
        metaType: "numeric",
        metaLabel: "Total",
        dataType: "string",
        key: "data",
        label: "Data",
      },
    ],
  },
  not_found: {
    head: "Not Found URLs (404s)",
    desc: "Top not found URLs sorted by hits [, avgts, cumts, maxts, mthd, proto]",
    id: "not_found",
    table: 1,
    index: 4,
    sort: { field: "hits", order: "DESC" },
    plot: [
      {
        className: "hits-visitors",
        label: "Hits/Visitors",
        chartType: "bar",
        chartReverse: 0,
        redrawOnExpand: 0,
        d3: {
          x: { key: ["method", "data", "protocol"] },
          y0: { key: "hits", label: "Hits" },
          y1: { key: "visitors", label: "Visitors" },
        },
      },
      {
        className: "bandwidth",
        label: "Tx. Amount",
        chartType: "bar",
        chartReverse: 0,
        redrawOnExpand: 0,
        d3: {
          x: { key: ["method", "protocol", "data"] },
          y0: { key: "bytes", label: "Tx. Amount", format: "bytes" },
        },
      },
    ],
    items: [
      {
        colWidth: "12%",
        meta: "count",
        dataType: "numeric",
        key: "hits",
        label: "Hits",
      },
      {
        colWidth: "12%",
        meta: "count",
        dataType: "numeric",
        key: "visitors",
        label: "Visitors",
      },
      {
        colWidth: "12%",
        meta: "count",
        dataType: "bytes",
        key: "bytes",
        label: "Tx. Amount",
      },
      { colWidth: "6%", dataType: "string", key: "method", label: "Method" },
      {
        colWidth: "7%",
        dataType: "string",
        key: "protocol",
        label: "Protocol",
      },
      {
        className: "trunc",
        colWidth: "100%",
        meta: "unique",
        metaType: "numeric",
        metaLabel: "Total",
        dataType: "string",
        key: "data",
        label: "Data",
      },
    ],
  },
  hosts: {
    head: "Visitor Hostnames and IPs",
    desc: "Top visitor hosts sorted by hits [, avgts, cumts, maxts]",
    id: "hosts",
    table: 1,
    index: 5,
    sort: { field: "hits", order: "DESC" },
    plot: [
      {
        className: "hits-visitors",
        label: "Hits/Visitors",
        chartType: "bar",
        chartReverse: 0,
        redrawOnExpand: 0,
        d3: {
          y0: { key: "hits", label: "Hits" },
          y1: { key: "visitors", label: "Visitors" },
        },
      },
      {
        className: "bandwidth",
        label: "Tx. Amount",
        chartType: "bar",
        chartReverse: 0,
        redrawOnExpand: 0,
        d3: { y0: { key: "bytes", label: "Tx. Amount", format: "bytes" } },
      },
    ],
    items: [
      {
        colWidth: "12%",
        meta: "count",
        dataType: "numeric",
        key: "hits",
        label: "Hits",
      },
      {
        colWidth: "12%",
        meta: "count",
        dataType: "numeric",
        key: "visitors",
        label: "Visitors",
      },
      {
        colWidth: "12%",
        meta: "count",
        dataType: "bytes",
        key: "bytes",
        label: "Tx. Amount",
      },
      {
        className: "trunc",
        colWidth: "100%",
        meta: "unique",
        metaType: "numeric",
        metaLabel: "Total",
        dataType: "string",
        key: "data",
        label: "Data",
      },
    ],
  },
  os: {
    head: "Operating Systems",
    desc: "Top Operating Systems sorted by hits [, avgts, cumts, maxts]",
    id: "os",
    table: 1,
    index: 6,
    sort: { field: "hits", order: "DESC" },
    plot: [
      {
        className: "hits-visitors",
        label: "Hits/Visitors",
        chartType: "bar",
        chartReverse: 0,
        redrawOnExpand: 1,
        d3: {
          y0: { key: "hits", label: "Hits" },
          y1: { key: "visitors", label: "Visitors" },
        },
      },
      {
        className: "bandwidth",
        label: "Tx. Amount",
        chartType: "bar",
        chartReverse: 0,
        redrawOnExpand: 1,
        d3: { y0: { key: "bytes", label: "Tx. Amount", format: "bytes" } },
      },
    ],
    items: [
      {
        colWidth: "12%",
        meta: "count",
        dataType: "numeric",
        key: "hits",
        label: "Hits",
      },
      {
        colWidth: "12%",
        meta: "count",
        dataType: "numeric",
        key: "visitors",
        label: "Visitors",
      },
      {
        colWidth: "12%",
        meta: "count",
        dataType: "bytes",
        key: "bytes",
        label: "Tx. Amount",
      },
      {
        className: "trunc",
        colWidth: "100%",
        meta: "unique",
        metaType: "numeric",
        metaLabel: "Total",
        dataType: "string",
        key: "data",
        label: "Data",
      },
    ],
  },
  browsers: {
    head: "Browsers",
    desc: "Top Browsers sorted by hits [, avgts, cumts, maxts]",
    id: "browsers",
    table: 1,
    index: 7,
    sort: { field: "hits", order: "DESC" },
    plot: [
      {
        className: "hits-visitors",
        label: "Hits/Visitors",
        chartType: "bar",
        chartReverse: 0,
        redrawOnExpand: 1,
        d3: {
          y0: { key: "hits", label: "Hits" },
          y1: { key: "visitors", label: "Visitors" },
        },
      },
      {
        className: "bandwidth",
        label: "Tx. Amount",
        chartType: "bar",
        chartReverse: 0,
        redrawOnExpand: 1,
        d3: { y0: { key: "bytes", label: "Tx. Amount", format: "bytes" } },
      },
    ],
    items: [
      {
        colWidth: "12%",
        meta: "count",
        dataType: "numeric",
        key: "hits",
        label: "Hits",
      },
      {
        colWidth: "12%",
        meta: "count",
        dataType: "numeric",
        key: "visitors",
        label: "Visitors",
      },
      {
        colWidth: "12%",
        meta: "count",
        dataType: "bytes",
        key: "bytes",
        label: "Tx. Amount",
      },
      {
        className: "trunc",
        colWidth: "100%",
        meta: "unique",
        metaType: "numeric",
        metaLabel: "Total",
        dataType: "string",
        key: "data",
        label: "Data",
      },
    ],
  },
  visit_time: {
    head: "Time Distribution",
    desc: "Data sorted by hour [, avgts, cumts, maxts]",
    id: "visit_time",
    table: 1,
    index: 8,
    sort: { field: "data", order: "ASC" },
    plot: [
      {
        className: "hits-visitors",
        label: "Hits/Visitors",
        chartType: "area-spline",
        chartReverse: 0,
        redrawOnExpand: 1,
        d3: {
          y0: { key: "hits", label: "Hits" },
          y1: { key: "visitors", label: "Visitors" },
        },
      },
      {
        className: "bandwidth",
        label: "Tx. Amount",
        chartType: "area-spline",
        chartReverse: 0,
        redrawOnExpand: 1,
        d3: { y0: { key: "bytes", label: "Tx. Amount", format: "bytes" } },
      },
    ],
    items: [
      {
        colWidth: "12%",
        meta: "count",
        dataType: "numeric",
        key: "hits",
        label: "Hits",
      },
      {
        colWidth: "12%",
        meta: "count",
        dataType: "numeric",
        key: "visitors",
        label: "Visitors",
      },
      {
        colWidth: "12%",
        meta: "count",
        dataType: "bytes",
        key: "bytes",
        label: "Tx. Amount",
      },
      {
        className: "trunc",
        colWidth: "100%",
        meta: "unique",
        metaType: "numeric",
        metaLabel: "Total",
        dataType: "string",
        key: "data",
        label: "Data",
      },
    ],
  },
  referring_sites: {
    head: "Referring Sites",
    desc: "Top Referring Sites sorted by hits [, avgts, cumts, maxts]",
    id: "referring_sites",
    table: 1,
    index: 9,
    sort: { field: "hits", order: "DESC" },
    plot: [
      {
        className: "hits-visitors",
        label: "Hits/Visitors",
        chartType: "bar",
        chartReverse: 0,
        redrawOnExpand: 0,
        d3: {
          y0: { key: "hits", label: "Hits" },
          y1: { key: "visitors", label: "Visitors" },
        },
      },
      {
        className: "bandwidth",
        label: "Tx. Amount",
        chartType: "bar",
        chartReverse: 0,
        redrawOnExpand: 0,
        d3: { y0: { key: "bytes", label: "Tx. Amount", format: "bytes" } },
      },
    ],
    items: [
      {
        colWidth: "12%",
        meta: "count",
        dataType: "numeric",
        key: "hits",
        label: "Hits",
      },
      {
        colWidth: "12%",
        meta: "count",
        dataType: "numeric",
        key: "visitors",
        label: "Visitors",
      },
      {
        colWidth: "12%",
        meta: "count",
        dataType: "bytes",
        key: "bytes",
        label: "Tx. Amount",
      },
      {
        className: "trunc",
        colWidth: "100%",
        meta: "unique",
        metaType: "numeric",
        metaLabel: "Total",
        dataType: "string",
        key: "data",
        label: "Data",
      },
    ],
  },
  status_codes: {
    head: "HTTP Status Codes",
    desc: "Top HTTP Status Codes sorted by hits [, avgts, cumts, maxts]",
    id: "status_codes",
    table: 1,
    index: 10,
    sort: { field: "hits", order: "DESC" },
    plot: [
      {
        className: "hits-visitors",
        label: "Hits/Visitors",
        chartType: "bar",
        chartReverse: 0,
        redrawOnExpand: 1,
        d3: {
          y0: { key: "hits", label: "Hits" },
          y1: { key: "visitors", label: "Visitors" },
        },
      },
      {
        className: "bandwidth",
        label: "Tx. Amount",
        chartType: "bar",
        chartReverse: 0,
        redrawOnExpand: 1,
        d3: { y0: { key: "bytes", label: "Tx. Amount", format: "bytes" } },
      },
    ],
    items: [
      {
        colWidth: "12%",
        meta: "count",
        dataType: "numeric",
        key: "hits",
        label: "Hits",
      },
      {
        colWidth: "12%",
        meta: "count",
        dataType: "numeric",
        key: "visitors",
        label: "Visitors",
      },
      {
        colWidth: "12%",
        meta: "count",
        dataType: "bytes",
        key: "bytes",
        label: "Tx. Amount",
      },
      {
        className: "trunc",
        colWidth: "100%",
        meta: "unique",
        metaType: "numeric",
        metaLabel: "Total",
        dataType: "string",
        key: "data",
        label: "Data",
      },
    ],
  },
};

var json_data = {
  general: {
    start_date: "08/Oct/2022",
    end_date: "24/Oct/2022",
    date_time: "2022-10-24 23:44:02 +0700",
    total_requests: 159,
    valid_requests: 159,
    failed_requests: 0,
    generation_time: 1,
    unique_visitors: 3,
    unique_files: 33,
    excluded_hits: 0,
    unique_referrers: 0,
    unique_not_found: 2,
    unique_static_files: 9,
    log_size: 37400,
    bandwidth: 2259569,
    log_path: ["/var/log/httpd/access_log"],
  },
  visitors: {
    metadata: {
      bytes: {
        total: { value: 2259569 },
        avg: { value: 753189, percent: "33.33" },
        max: { value: 2047512, percent: "90.62" },
        min: { value: 72643, percent: "3.21" },
      },
      visitors: {
        total: { value: 3 },
        avg: { value: 1, percent: "33.33" },
        max: { value: 1, percent: "33.33" },
        min: { value: 1, percent: "33.33" },
      },
      hits: {
        total: { value: 159 },
        avg: { value: 53, percent: "33.33" },
        max: { value: 95, percent: "59.75" },
        min: { value: 21, percent: "13.21" },
      },
      data: { total: { value: 3 } },
    },
    data: [
      {
        hits: { count: 95, percent: "59.75" },
        visitors: { count: 1, percent: "33.33" },
        bytes: { count: 2047512, percent: "90.62" },
        data: "20221024",
      },
      {
        hits: { count: 43, percent: "27.04" },
        visitors: { count: 1, percent: "33.33" },
        bytes: { count: 139414, percent: "6.17" },
        data: "20221011",
      },
      {
        hits: { count: 21, percent: "13.21" },
        visitors: { count: 1, percent: "33.33" },
        bytes: { count: 72643, percent: "3.21" },
        data: "20221008",
      },
    ],
  },
  realtime_requests: {
    metadata: {
      bytes: {
        total: { value: 2198907 },
        avg: { value: 66633, percent: "3.03" },
        max: { value: 1774419, percent: "80.70" },
        min: { value: 0, percent: "0.00" },
      },
      visitors: {
        total: { value: 48 },
        avg: { value: 1, percent: "2.08" },
        max: { value: 3, percent: "6.25" },
        min: { value: 1, percent: "2.08" },
      },
      hits: {
        total: { value: 119 },
        avg: { value: 3, percent: "2.52" },
        max: { value: 20, percent: "16.81" },
        min: { value: 1, percent: "0.84" },
      },
      data: { total: { value: 33 } },
    },
    data: [],
  },
  requests: {
    metadata: {
      bytes: {
        total: { value: 2198907 },
        avg: { value: 66633, percent: "3.03" },
        max: { value: 1774419, percent: "80.70" },
        min: { value: 0, percent: "0.00" },
      },
      visitors: {
        total: { value: 48 },
        avg: { value: 1, percent: "2.08" },
        max: { value: 3, percent: "6.25" },
        min: { value: 1, percent: "2.08" },
      },
      hits: {
        total: { value: 119 },
        avg: { value: 3, percent: "2.52" },
        max: { value: 20, percent: "16.81" },
        min: { value: 1, percent: "0.84" },
      },
      data: { total: { value: 33 } },
    },
    data: [
      {
        hits: { count: 20, percent: "12.58" },
        visitors: { count: 3, percent: "100.00" },
        bytes: { count: 89021, percent: "3.94" },
        method: "GET",
        protocol: "HTTP/1.1",
        data: "/dvwa/index.php",
      },
      {
        hits: { count: 14, percent: "8.81" },
        visitors: { count: 0, percent: "0.00" },
        bytes: { count: 0, percent: "0.00" },
        method: "---",
        protocol: "---",
        data: "-",
      },
      {
        hits: { count: 13, percent: "8.18" },
        visitors: { count: 1, percent: "33.33" },
        bytes: { count: 1774419, percent: "78.53" },
        method: "GET",
        protocol: "HTTP/1.1",
        data: "/report.html",
      },
      {
        hits: { count: 10, percent: "6.29" },
        visitors: { count: 3, percent: "100.00" },
        bytes: { count: 41308, percent: "1.83" },
        method: "GET",
        protocol: "HTTP/1.1",
        data: "/dvwa/vulnerabilities/sqli/",
      },
      {
        hits: { count: 7, percent: "4.40" },
        visitors: { count: 2, percent: "66.67" },
        bytes: { count: 9951, percent: "0.44" },
        method: "GET",
        protocol: "HTTP/1.1",
        data: "/dvwa/login.php",
      },
      {
        hits: { count: 6, percent: "3.77" },
        visitors: { count: 1, percent: "33.33" },
        bytes: { count: 49807, percent: "2.20" },
        method: "POST",
        protocol: "HTTP/1.1",
        data: "/dvwa/vulnerabilities/javascript/",
      },
      {
        hits: { count: 4, percent: "2.52" },
        visitors: { count: 3, percent: "100.00" },
        bytes: { count: 18412, percent: "0.81" },
        method: "GET",
        protocol: "HTTP/1.1",
        data: "/dvwa/vulnerabilities/xss_d/",
      },
      {
        hits: { count: 4, percent: "2.52" },
        visitors: { count: 3, percent: "100.00" },
        bytes: { count: 17110, percent: "0.76" },
        method: "GET",
        protocol: "HTTP/1.1",
        data: "/dvwa/vulnerabilities/xss_r/",
      },
      {
        hits: { count: 4, percent: "2.52" },
        visitors: { count: 2, percent: "66.67" },
        bytes: { count: 16388, percent: "0.73" },
        method: "GET",
        protocol: "HTTP/1.1",
        data: "/dvwa/vulnerabilities/fi/?page=include.php",
      },
      {
        hits: { count: 4, percent: "2.52" },
        visitors: { count: 2, percent: "66.67" },
        bytes: { count: 16168, percent: "0.72" },
        method: "GET",
        protocol: "HTTP/1.1",
        data: "/dvwa/vulnerabilities/upload/",
      },
      {
        hits: { count: 4, percent: "2.52" },
        visitors: { count: 2, percent: "66.67" },
        bytes: { count: 21246, percent: "0.94" },
        method: "GET",
        protocol: "HTTP/1.1",
        data: "/dvwa/security.php",
      },
      {
        hits: { count: 3, percent: "1.89" },
        visitors: { count: 2, percent: "66.67" },
        bytes: { count: 13647, percent: "0.60" },
        method: "GET",
        protocol: "HTTP/1.1",
        data: "/dvwa/vulnerabilities/captcha/",
      },
      {
        hits: { count: 3, percent: "1.89" },
        visitors: { count: 2, percent: "66.67" },
        bytes: { count: 0, percent: "0.00" },
        method: "POST",
        protocol: "HTTP/1.1",
        data: "/dvwa/login.php",
      },
      {
        hits: { count: 2, percent: "1.26" },
        visitors: { count: 1, percent: "33.33" },
        bytes: { count: 9354, percent: "0.41" },
        method: "GET",
        protocol: "HTTP/1.1",
        data: "/dvwa/vulnerabilities/csrf/",
      },
      {
        hits: { count: 2, percent: "1.26" },
        visitors: { count: 2, percent: "66.67" },
        bytes: { count: 12243, percent: "0.54" },
        method: "GET",
        protocol: "HTTP/1.1",
        data: "/dvwa/vulnerabilities/javascript/",
      },
      {
        hits: { count: 2, percent: "1.26" },
        visitors: { count: 2, percent: "66.67" },
        bytes: { count: 0, percent: "0.00" },
        method: "POST",
        protocol: "HTTP/1.1",
        data: "/dvwa/security.php",
      },
      {
        hits: { count: 1, percent: "0.63" },
        visitors: { count: 1, percent: "33.33" },
        bytes: { count: 4866, percent: "0.22" },
        method: "GET",
        protocol: "HTTP/1.1",
        data: "/dvwa/vulnerabilities/xss_s/",
      },
      {
        hits: { count: 1, percent: "0.63" },
        visitors: { count: 1, percent: "33.33" },
        bytes: { count: 204, percent: "0.01" },
        method: "GET",
        protocol: "HTTP/1.1",
        data: "/dvwa/vulnerabilities/xss_r/?name=&lt;script&gt;alert(&#39;XXS+Attacked&#39;)&lt;/script&gt;&amp;user_token=887e2006faf1ef4032d1c95b740bbc9e",
      },
      {
        hits: { count: 1, percent: "0.63" },
        visitors: { count: 1, percent: "33.33" },
        bytes: { count: 4742, percent: "0.21" },
        method: "GET",
        protocol: "HTTP/1.1",
        data: "/dvwa/vulnerabilities/csrf/?password_current=123&amp;password_new=123&amp;password_conf=123&amp;Change=Change&amp;user_token=424c010f2d347ec6d9361762ec43924e",
      },
      {
        hits: { count: 1, percent: "0.63" },
        visitors: { count: 1, percent: "33.33" },
        bytes: { count: 4267, percent: "0.19" },
        method: "GET",
        protocol: "HTTP/1.1",
        data: "/dvwa/vulnerabilities/csp/",
      },
      {
        hits: { count: 1, percent: "0.63" },
        visitors: { count: 1, percent: "33.33" },
        bytes: { count: 204, percent: "0.01" },
        method: "GET",
        protocol: "HTTP/1.1",
        data: "/dvwa/vulnerabilities/sqli/?id=%&#39;+or+&#39;0&#39;=&#39;0&amp;Submit=Submit&amp;user_token=6baa787eef8dd909787e9a97202d6f91",
      },
      {
        hits: { count: 1, percent: "0.63" },
        visitors: { count: 1, percent: "33.33" },
        bytes: { count: 204, percent: "0.01" },
        method: "GET",
        protocol: "HTTP/1.1",
        data: "/dvwa/vulnerabilities/xss_r/?name=&lt;script&gt;alert(&#39;XXS+Attacked&#39;)&lt;/script&gt;&amp;user_token=21fb49db4be756052a44afeea4e56f8b",
      },
      {
        hits: { count: 1, percent: "0.63" },
        visitors: { count: 1, percent: "33.33" },
        bytes: { count: 204, percent: "0.01" },
        method: "GET",
        protocol: "HTTP/1.1",
        data: "/dvwa/vulnerabilities/sqli/?id=fpw=(select%20convert(int%2cCHAR(65)))&amp;Submit=Submit&amp;user_token=b7ffdc3fdcffbadf5338762ac81df6c7",
      },
      {
        hits: { count: 1, percent: "0.63" },
        visitors: { count: 1, percent: "33.33" },
        bytes: { count: 4219, percent: "0.19" },
        method: "GET",
        protocol: "HTTP/1.1",
        data: "/dvwa/vulnerabilities/sqli_blind/",
      },
      {
        hits: { count: 1, percent: "0.63" },
        visitors: { count: 1, percent: "33.33" },
        bytes: { count: 204, percent: "0.01" },
        method: "GET",
        protocol: "HTTP/1.1",
        data: "/dvwa/vulnerabilities/sqli/?id=%&#39;+or+&#39;0&#39;=&#39;0&amp;Submit=Submit",
      },
      {
        hits: { count: 1, percent: "0.63" },
        visitors: { count: 1, percent: "33.33" },
        bytes: { count: 89519, percent: "3.96" },
        method: "GET",
        protocol: "HTTP/1.1",
        data: "/info.php",
      },
      {
        hits: { count: 1, percent: "0.63" },
        visitors: { count: 1, percent: "33.33" },
        bytes: { count: 204, percent: "0.01" },
        method: "GET",
        protocol: "HTTP/1.1",
        data: "/dvwa/vulnerabilities/sqli/?id=%&#39;+or+&#39;0&#39;=&#39;0&amp;Submit=Submit&amp;user_token=da7bc47f8a2f651a1b72beed24fe4afa",
      },
      {
        hits: { count: 1, percent: "0.63" },
        visitors: { count: 1, percent: "33.33" },
        bytes: { count: 0, percent: "0.00" },
        method: "GET",
        protocol: "HTTP/1.1",
        data: "/dvwa/logout.php",
      },
      {
        hits: { count: 1, percent: "0.63" },
        visitors: { count: 1, percent: "33.33" },
        bytes: { count: 180, percent: "0.01" },
        method: "GET",
        protocol: "HTTP/1.1",
        data: "/",
      },
      {
        hits: { count: 1, percent: "0.63" },
        visitors: { count: 1, percent: "33.33" },
        bytes: { count: 204, percent: "0.01" },
        method: "GET",
        protocol: "HTTP/1.1",
        data: "/dvwa/vulnerabilities/sqli/?id=%&#39;+or+&#39;0&#39;=&#39;0&amp;Submit=Submit&amp;user_token=e18580b2cccf1663aa02eee362deaad7",
      },
      {
        hits: { count: 1, percent: "0.63" },
        visitors: { count: 1, percent: "33.33" },
        bytes: { count: 204, percent: "0.01" },
        method: "GET",
        protocol: "HTTP/1.1",
        data: "/dvwa/vulnerabilities/sqli/?id=%&#39;+or+&#39;0&#39;=&#39;0&amp;Submit=Submit&amp;user_token=41580c0eb9c0e2e8e13eb983710cffb2",
      },
      {
        hits: { count: 1, percent: "0.63" },
        visitors: { count: 1, percent: "33.33" },
        bytes: { count: 204, percent: "0.01" },
        method: "GET",
        protocol: "HTTP/1.1",
        data: "/dvwa/vulnerabilities/sqli/?id=%&#39;+or+&#39;0&#39;=&#39;0&amp;Submit=Submit&amp;user_token=c748e5a7a0f2e1f2d9cd30779d74ad72",
      },
      {
        hits: { count: 1, percent: "0.63" },
        visitors: { count: 1, percent: "33.33" },
        bytes: { count: 204, percent: "0.01" },
        method: "GET",
        protocol: "HTTP/1.1",
        data: "/dvwa/vulnerabilities/xss_r/?name=&lt;script&gt;alert(&#39;XXS+Attacked&#39;)&lt;/script&gt;",
      },
    ],
  },
  static_requests: {
    metadata: {
      bytes: {
        total: { value: 55931 },
        avg: { value: 6214, percent: "11.11" },
        max: { value: 27264, percent: "48.75" },
        min: { value: 421, percent: "0.75" },
      },
      visitors: {
        total: { value: 10 },
        avg: { value: 1, percent: "10.00" },
        max: { value: 2, percent: "20.00" },
        min: { value: 1, percent: "10.00" },
      },
      hits: {
        total: { value: 19 },
        avg: { value: 2, percent: "10.53" },
        max: { value: 3, percent: "15.79" },
        min: { value: 1, percent: "5.26" },
      },
      data: { total: { value: 9 } },
    },
    data: [
      {
        hits: { count: 3, percent: "1.89" },
        visitors: { count: 1, percent: "33.33" },
        bytes: { count: 2526, percent: "0.11" },
        method: "GET",
        protocol: "HTTP/1.1",
        data: "/dvwa/dvwa/css/login.css",
      },
      {
        hits: { count: 3, percent: "1.89" },
        visitors: { count: 1, percent: "33.33" },
        bytes: { count: 27264, percent: "1.21" },
        method: "GET",
        protocol: "HTTP/1.1",
        data: "/dvwa/dvwa/images/login_logo.png",
      },
      {
        hits: { count: 2, percent: "1.26" },
        visitors: { count: 2, percent: "66.67" },
        bytes: { count: 1522, percent: "0.07" },
        method: "GET",
        protocol: "HTTP/1.1",
        data: "/dvwa/dvwa/images/lock.png",
      },
      {
        hits: { count: 2, percent: "1.26" },
        visitors: { count: 1, percent: "33.33" },
        bytes: { count: 8052, percent: "0.36" },
        method: "GET",
        protocol: "HTTP/1.1",
        data: "/dvwa/dvwa/css/main.css",
      },
      {
        hits: { count: 2, percent: "1.26" },
        visitors: { count: 1, percent: "33.33" },
        bytes: { count: 2060, percent: "0.09" },
        method: "GET",
        protocol: "HTTP/1.1",
        data: "/dvwa/dvwa/js/dvwaPage.js",
      },
      {
        hits: { count: 2, percent: "1.26" },
        visitors: { count: 1, percent: "33.33" },
        bytes: { count: 10088, percent: "0.45" },
        method: "GET",
        protocol: "HTTP/1.1",
        data: "/dvwa/dvwa/images/logo.png",
      },
      {
        hits: { count: 2, percent: "1.26" },
        visitors: { count: 1, percent: "33.33" },
        bytes: { count: 2812, percent: "0.12" },
        method: "GET",
        protocol: "HTTP/1.1",
        data: "/dvwa/favicon.ico",
      },
      {
        hits: { count: 2, percent: "1.26" },
        visitors: { count: 1, percent: "33.33" },
        bytes: { count: 1186, percent: "0.05" },
        method: "GET",
        protocol: "HTTP/1.1",
        data: "/dvwa//dvwa/js/add_event_listeners.js",
      },
      {
        hits: { count: 1, percent: "0.63" },
        visitors: { count: 1, percent: "33.33" },
        bytes: { count: 421, percent: "0.02" },
        method: "GET",
        protocol: "HTTP/1.1",
        data: "/dvwa/vulnerabilities/csp/source/impossible.js",
      },
    ],
  },
  not_found: {
    metadata: {
      bytes: {
        total: { value: 4731 },
        avg: { value: 2365, percent: "49.99" },
        max: { value: 4104, percent: "86.75" },
        min: { value: 627, percent: "13.25" },
      },
      visitors: {
        total: { value: 0 },
        avg: { value: 0, percent: "0.00" },
        max: { value: 0, percent: "0.00" },
        min: { value: 0, percent: "0.00" },
      },
      hits: {
        total: { value: 21 },
        avg: { value: 10, percent: "47.62" },
        max: { value: 18, percent: "85.71" },
        min: { value: 3, percent: "14.29" },
      },
      data: { total: { value: 2 } },
    },
    data: [
      {
        hits: { count: 18, percent: "11.32" },
        visitors: { count: 0, percent: "0.00" },
        bytes: { count: 4104, percent: "0.18" },
        method: "GET",
        protocol: "HTTP/1.1",
        data: "/dvwa/js/add_event_listeners.js",
      },
      {
        hits: { count: 3, percent: "1.89" },
        visitors: { count: 0, percent: "0.00" },
        bytes: { count: 627, percent: "0.03" },
        method: "GET",
        protocol: "HTTP/1.1",
        data: "/favicon.ico",
      },
    ],
  },
  hosts: {
    metadata: {
      bytes: {
        total: { value: 2259569 },
        avg: { value: 2259569, percent: "100.00" },
        max: { value: 2259569, percent: "100.00" },
        min: { value: 2259569, percent: "100.00" },
      },
      visitors: {
        total: { value: 3 },
        avg: { value: 3, percent: "100.00" },
        max: { value: 3, percent: "100.00" },
        min: { value: 3, percent: "100.00" },
      },
      hits: {
        total: { value: 159 },
        avg: { value: 159, percent: "100.00" },
        max: { value: 159, percent: "100.00" },
        min: { value: 159, percent: "100.00" },
      },
      data: { total: { value: 1 } },
    },
    data: [
      {
        hits: { count: 159, percent: "100.00" },
        visitors: { count: 3, percent: "100.00" },
        bytes: { count: 2259569, percent: "100.00" },
        data: "192.168.88.1",
      },
    ],
  },
  os: {
    metadata: {
      bytes: {
        total: { value: 2259569 },
        avg: { value: 1129784, percent: "50.00" },
        max: { value: 2259569, percent: "100.00" },
        min: { value: 0, percent: "0.00" },
      },
      visitors: {
        total: { value: 3 },
        avg: { value: 1, percent: "33.33" },
        max: { value: 3, percent: "100.00" },
        min: { value: 3, percent: "100.00" },
      },
      hits: {
        total: { value: 159 },
        avg: { value: 79, percent: "49.69" },
        max: { value: 145, percent: "91.19" },
        min: { value: 14, percent: "8.81" },
      },
      data: { total: { value: 2 } },
    },
    data: [
      {
        hits: { count: 145, percent: "91.19" },
        visitors: { count: 3, percent: "100.00" },
        bytes: { count: 2259569, percent: "100.00" },
        data: "Windows",
        items: [
          {
            hits: { count: 145, percent: "91.19" },
            visitors: { count: 3, percent: "100.00" },
            bytes: { count: 2259569, percent: "100.00" },
            data: "Windows 10",
          },
        ],
      },
      {
        hits: { count: 14, percent: "8.81" },
        visitors: { count: 0, percent: "0.00" },
        bytes: { count: 0, percent: "0.00" },
        data: "Unknown",
        items: [
          {
            hits: { count: 14, percent: "8.81" },
            visitors: { count: 0, percent: "0.00" },
            bytes: { count: 0, percent: "0.00" },
            data: "Unknown",
          },
        ],
      },
    ],
  },
  browsers: {
    metadata: {
      bytes: {
        total: { value: 2259569 },
        avg: { value: 1129784, percent: "50.00" },
        max: { value: 2259569, percent: "100.00" },
        min: { value: 0, percent: "0.00" },
      },
      visitors: {
        total: { value: 3 },
        avg: { value: 1, percent: "33.33" },
        max: { value: 3, percent: "100.00" },
        min: { value: 3, percent: "100.00" },
      },
      hits: {
        total: { value: 159 },
        avg: { value: 79, percent: "49.69" },
        max: { value: 145, percent: "91.19" },
        min: { value: 14, percent: "8.81" },
      },
      data: { total: { value: 2 } },
    },
    data: [
      {
        hits: { count: 145, percent: "91.19" },
        visitors: { count: 3, percent: "100.00" },
        bytes: { count: 2259569, percent: "100.00" },
        data: "Chrome",
        items: [
          {
            hits: { count: 145, percent: "91.19" },
            visitors: { count: 3, percent: "100.00" },
            bytes: { count: 2259569, percent: "100.00" },
            data: "Chrome/106.0.0.0",
          },
        ],
      },
      {
        hits: { count: 14, percent: "8.81" },
        visitors: { count: 0, percent: "0.00" },
        bytes: { count: 0, percent: "0.00" },
        data: "Unknown",
        items: [
          {
            hits: { count: 14, percent: "8.81" },
            visitors: { count: 0, percent: "0.00" },
            bytes: { count: 0, percent: "0.00" },
            data: "Unknown",
          },
        ],
      },
    ],
  },
  visit_time: {
    metadata: {
      bytes: {
        total: { value: 2259569 },
        avg: { value: 753189, percent: "33.33" },
        max: { value: 2047512, percent: "90.62" },
        min: { value: 72643, percent: "3.21" },
      },
      visitors: {
        total: { value: 3 },
        avg: { value: 1, percent: "33.33" },
        max: { value: 1, percent: "33.33" },
        min: { value: 1, percent: "33.33" },
      },
      hits: {
        total: { value: 159 },
        avg: { value: 53, percent: "33.33" },
        max: { value: 95, percent: "59.75" },
        min: { value: 21, percent: "13.21" },
      },
      data: { total: { value: 3 } },
    },
    data: [
      {
        hits: { count: 21, percent: "13.21" },
        visitors: { count: 1, percent: "33.33" },
        bytes: { count: 72643, percent: "3.21" },
        data: "11",
      },
      {
        hits: { count: 43, percent: "27.04" },
        visitors: { count: 1, percent: "33.33" },
        bytes: { count: 139414, percent: "6.17" },
        data: "20",
      },
      {
        hits: { count: 95, percent: "59.75" },
        visitors: { count: 1, percent: "33.33" },
        bytes: { count: 2047512, percent: "90.62" },
        data: "23",
      },
    ],
  },
  referring_sites: {
    metadata: {
      bytes: {
        total: { value: 380620 },
        avg: { value: 190310, percent: "50.00" },
        max: { value: 274823, percent: "72.20" },
        min: { value: 105797, percent: "27.80" },
      },
      visitors: {
        total: { value: 4 },
        avg: { value: 2, percent: "50.00" },
        max: { value: 3, percent: "75.00" },
        min: { value: 1, percent: "25.00" },
      },
      hits: {
        total: { value: 117 },
        avg: { value: 58, percent: "49.57" },
        max: { value: 79, percent: "67.52" },
        min: { value: 38, percent: "32.48" },
      },
      data: { total: { value: 2 } },
    },
    data: [
      {
        hits: { count: 79, percent: "49.69" },
        visitors: { count: 3, percent: "100.00" },
        bytes: { count: 274823, percent: "12.16" },
        data: "lab.ktm.dtu",
      },
      {
        hits: { count: 38, percent: "23.90" },
        visitors: { count: 1, percent: "33.33" },
        bytes: { count: 105797, percent: "4.68" },
        data: "192.168.88.100",
      },
    ],
  },
  status_codes: {
    metadata: {
      bytes: {
        total: { value: 2259569 },
        avg: { value: 451913, percent: "20.00" },
        max: { value: 2252798, percent: "99.70" },
        min: { value: 0, percent: "0.00" },
      },
      visitors: {
        total: { value: 7 },
        avg: { value: 1, percent: "14.29" },
        max: { value: 3, percent: "42.86" },
        min: { value: 1, percent: "14.29" },
      },
      hits: {
        total: { value: 159 },
        avg: { value: 31, percent: "19.50" },
        max: { value: 94, percent: "59.12" },
        min: { value: 8, percent: "5.03" },
      },
      data: { total: { value: 5 } },
    },
    data: [
      {
        hits: { count: 94, percent: "59.12" },
        visitors: { count: 3, percent: "100.00" },
        bytes: { count: 2252798, percent: "99.70" },
        data: "2xx Success",
        items: [
          {
            hits: { count: 94, percent: "59.12" },
            visitors: { count: 3, percent: "100.00" },
            bytes: { count: 2252798, percent: "99.70" },
            data: "200 - OK: The request sent by the client was successful",
          },
        ],
      },
      {
        hits: { count: 35, percent: "22.01" },
        visitors: { count: 0, percent: "0.00" },
        bytes: { count: 4731, percent: "0.21" },
        data: "4xx Client Errors",
        items: [
          {
            hits: { count: 21, percent: "13.21" },
            visitors: { count: 0, percent: "0.00" },
            bytes: { count: 4731, percent: "0.21" },
            data: "404 - Not Found: Requested resource could not be found",
          },
          {
            hits: { count: 14, percent: "8.81" },
            visitors: { count: 0, percent: "0.00" },
            bytes: { count: 0, percent: "0.00" },
            data: "408 - Request Timeout: Server timed out waiting for the request",
          },
        ],
      },
      {
        hits: { count: 30, percent: "18.87" },
        visitors: { count: 4, percent: "133.33" },
        bytes: { count: 2040, percent: "0.09" },
        data: "3xx Redirection",
        items: [
          {
            hits: { count: 22, percent: "13.84" },
            visitors: { count: 3, percent: "100.00" },
            bytes: { count: 2040, percent: "0.09" },
            data: "302 - Moved Temporarily (redirect)",
          },
          {
            hits: { count: 8, percent: "5.03" },
            visitors: { count: 1, percent: "33.33" },
            bytes: { count: 0, percent: "0.00" },
            data: "304 - Not Modified: Resource has not been modified",
          },
        ],
      },
    ],
  },
};
